// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finding_events.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFindingEvent = `-- name: CreateFindingEvent :one
INSERT INTO finding_events (
    id, finding_id, event_type, actor,
    old_value, new_value, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING created_at
`

type CreateFindingEventParams struct {
	ID        uuid.UUID       `json:"id"`
	FindingID uuid.UUID       `json:"finding_id"`
	EventType string          `json:"event_type"`
	Actor     string          `json:"actor"`
	OldValue  pgtype.Text     `json:"old_value"`
	NewValue  pgtype.Text     `json:"new_value"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateFindingEvent(ctx context.Context, arg CreateFindingEventParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createFindingEvent,
		arg.ID,
		arg.FindingID,
		arg.EventType,
		arg.Actor,
		arg.OldValue,
		arg.NewValue,
		arg.Metadata,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listEventsForFinding = `-- name: ListEventsForFinding :many
SELECT id, finding_id, event_type, actor,
       old_value, new_value, metadata, created_at
FROM finding_events
WHERE finding_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEventsForFinding(ctx context.Context, findingID uuid.UUID) ([]FindingEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingEvent{}
	for rows.Next() {
		var i FindingEvent
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.EventType,
			&i.Actor,
			&i.OldValue,
			&i.NewValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
