// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (
    id, review_task_id, pull_request_id,
    file_path, start_line, end_line, symbol,
    category, confidence_tier, confidence_score, severity,
    title, body, suggestion,
    location_hash, content_hash,
    model_id, prompt_tokens, completion_tokens, metadata
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16,
    $17, $18, $19, $20
)
RETURNING created_at, updated_at
`

type CreateFindingParams struct {
	ID               uuid.UUID       `json:"id"`
	ReviewTaskID     uuid.UUID       `json:"review_task_id"`
	PullRequestID    uuid.UUID       `json:"pull_request_id"`
	FilePath         string          `json:"file_path"`
	StartLine        pgtype.Int4     `json:"start_line"`
	EndLine          pgtype.Int4     `json:"end_line"`
	Symbol           pgtype.Text     `json:"symbol"`
	Category         string          `json:"category"`
	ConfidenceTier   string          `json:"confidence_tier"`
	ConfidenceScore  float64         `json:"confidence_score"`
	Severity         string          `json:"severity"`
	Title            string          `json:"title"`
	Body             string          `json:"body"`
	Suggestion       pgtype.Text     `json:"suggestion"`
	LocationHash     string          `json:"location_hash"`
	ContentHash      pgtype.Text     `json:"content_hash"`
	ModelID          string          `json:"model_id"`
	PromptTokens     pgtype.Int4     `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4     `json:"completion_tokens"`
	Metadata         json.RawMessage `json:"metadata"`
}

type CreateFindingRow struct {
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (CreateFindingRow, error) {
	row := q.db.QueryRow(ctx, createFinding,
		arg.ID,
		arg.ReviewTaskID,
		arg.PullRequestID,
		arg.FilePath,
		arg.StartLine,
		arg.EndLine,
		arg.Symbol,
		arg.Category,
		arg.ConfidenceTier,
		arg.ConfidenceScore,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.Suggestion,
		arg.LocationHash,
		arg.ContentHash,
		arg.ModelID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Metadata,
	)
	var i CreateFindingRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const isFingerprintDismissed = `-- name: IsFingerprintDismissed :one
SELECT EXISTS(
    SELECT 1 FROM dismissed_fingerprints
    WHERE fingerprint = $1 AND repo_full_name = $2
) AS dismissed
`

type IsFingerprintDismissedParams struct {
	Fingerprint  string `json:"fingerprint"`
	RepoFullName string `json:"repo_full_name"`
}

func (q *Queries) IsFingerprintDismissed(ctx context.Context, arg IsFingerprintDismissedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFingerprintDismissed, arg.Fingerprint, arg.RepoFullName)
	var dismissed bool
	err := row.Scan(&dismissed)
	return dismissed, err
}

const listFindingsForPR = `-- name: ListFindingsForPR :many
SELECT id, review_task_id, pull_request_id,
       file_path, start_line, end_line, symbol,
       category, confidence_tier, confidence_score, severity,
       title, body, suggestion,
       location_hash, content_hash,
       posted_at, github_comment_id, addressed_in_next_commit,
       dismissed_at, dismissed_by,
       model_id, prompt_tokens, completion_tokens, metadata,
       created_at, updated_at
FROM findings
WHERE pull_request_id = $1
ORDER BY confidence_score DESC,
         CASE severity
             WHEN 'critical' THEN 1
             WHEN 'high'     THEN 2
             WHEN 'medium'   THEN 3
             WHEN 'low'      THEN 4
             WHEN 'info'     THEN 5
         END ASC
`

func (q *Queries) ListFindingsForPR(ctx context.Context, pullRequestID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsForPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewTaskID,
			&i.PullRequestID,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.Symbol,
			&i.Category,
			&i.ConfidenceTier,
			&i.ConfidenceScore,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Suggestion,
			&i.LocationHash,
			&i.ContentHash,
			&i.PostedAt,
			&i.GithubCommentID,
			&i.AddressedInNextCommit,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.ModelID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFindingAddressed = `-- name: MarkFindingAddressed :execrows
UPDATE findings
SET addressed_in_next_commit = true
WHERE id = $1
`

func (q *Queries) MarkFindingAddressed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markFindingAddressed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFindingPosted = `-- name: MarkFindingPosted :execrows
UPDATE findings
SET posted_at = now(), github_comment_id = $2
WHERE id = $1
`

type MarkFindingPostedParams struct {
	ID              uuid.UUID   `json:"id"`
	GithubCommentID pgtype.Int8 `json:"github_comment_id"`
}

func (q *Queries) MarkFindingPosted(ctx context.Context, arg MarkFindingPostedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFindingPosted, arg.ID, arg.GithubCommentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
