// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finding_events.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReactionsForFinding = `-- name: CountReactionsForFinding :one
SELECT
    COUNT(*) FILTER (WHERE event_type = 'thumbs_up') AS thumbs_up,
    COUNT(*) FILTER (WHERE event_type = 'thumbs_down') AS thumbs_down
FROM finding_events
WHERE finding_id = $1
`

type CountReactionsForFindingRow struct {
	ThumbsUp   int64 `json:"thumbs_up"`
	ThumbsDown int64 `json:"thumbs_down"`
}

func (q *Queries) CountReactionsForFinding(ctx context.Context, findingID uuid.UUID) (CountReactionsForFindingRow, error) {
	row := q.db.QueryRow(ctx, countReactionsForFinding, findingID)
	var i CountReactionsForFindingRow
	err := row.Scan(&i.ThumbsUp, &i.ThumbsDown)
	return i, err
}

const createFindingEvent = `-- name: CreateFindingEvent :exec
INSERT INTO finding_events (finding_id, event_type, actor, old_value, new_value, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (finding_id, event_type, actor)
    WHERE event_type IN ('thumbs_up', 'thumbs_down')
    DO NOTHING
`

type CreateFindingEventParams struct {
	FindingID uuid.UUID       `json:"finding_id"`
	EventType string          `json:"event_type"`
	Actor     string          `json:"actor"`
	OldValue  pgtype.Text     `json:"old_value"`
	NewValue  pgtype.Text     `json:"new_value"`
	Metadata  json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateFindingEvent(ctx context.Context, arg CreateFindingEventParams) error {
	_, err := q.db.Exec(ctx, createFindingEvent,
		arg.FindingID,
		arg.EventType,
		arg.Actor,
		arg.OldValue,
		arg.NewValue,
		arg.Metadata,
	)
	return err
}

const listEventsForFinding = `-- name: ListEventsForFinding :many
SELECT id, finding_id, event_type, actor, old_value, new_value, metadata, created_at FROM finding_events WHERE finding_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListEventsForFinding(ctx context.Context, findingID uuid.UUID) ([]FindingEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingEvent{}
	for rows.Next() {
		var i FindingEvent
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.EventType,
			&i.Actor,
			&i.OldValue,
			&i.NewValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
