// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (
    review_task_id, pull_request_id, pipeline_run_id,
    repo_full_name, file_path, start_line, end_line, symbol,
    category, confidence_tier, confidence_score, severity,
    title, body, suggestion, location_hash, content_hash, head_sha,
    suppression_reason,
    model_id, prompt_tokens, completion_tokens, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
RETURNING id, review_task_id, pull_request_id, pipeline_run_id, repo_full_name, file_path, start_line, end_line, symbol, category, confidence_tier, confidence_score, severity, title, body, suggestion, location_hash, content_hash, head_sha, posted_at, external_comment_id, addressed_status, suppression_reason, dismissed_at, dismissed_by, model_id, prompt_tokens, completion_tokens, metadata, created_at, updated_at
`

type CreateFindingParams struct {
	ReviewTaskID      uuid.UUID       `json:"review_task_id"`
	PullRequestID     uuid.UUID       `json:"pull_request_id"`
	PipelineRunID     uuid.UUID       `json:"pipeline_run_id"`
	RepoFullName      string          `json:"repo_full_name"`
	FilePath          string          `json:"file_path"`
	StartLine         pgtype.Int4     `json:"start_line"`
	EndLine           pgtype.Int4     `json:"end_line"`
	Symbol            string          `json:"symbol"`
	Category          string          `json:"category"`
	ConfidenceTier    string          `json:"confidence_tier"`
	ConfidenceScore   float64         `json:"confidence_score"`
	Severity          string          `json:"severity"`
	Title             string          `json:"title"`
	Body              string          `json:"body"`
	Suggestion        pgtype.Text     `json:"suggestion"`
	LocationHash      string          `json:"location_hash"`
	ContentHash       pgtype.Text     `json:"content_hash"`
	HeadSha           string          `json:"head_sha"`
	SuppressionReason pgtype.Text     `json:"suppression_reason"`
	ModelID           string          `json:"model_id"`
	PromptTokens      pgtype.Int4     `json:"prompt_tokens"`
	CompletionTokens  pgtype.Int4     `json:"completion_tokens"`
	Metadata          json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, createFinding,
		arg.ReviewTaskID,
		arg.PullRequestID,
		arg.PipelineRunID,
		arg.RepoFullName,
		arg.FilePath,
		arg.StartLine,
		arg.EndLine,
		arg.Symbol,
		arg.Category,
		arg.ConfidenceTier,
		arg.ConfidenceScore,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.Suggestion,
		arg.LocationHash,
		arg.ContentHash,
		arg.HeadSha,
		arg.SuppressionReason,
		arg.ModelID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Metadata,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ReviewTaskID,
		&i.PullRequestID,
		&i.PipelineRunID,
		&i.RepoFullName,
		&i.FilePath,
		&i.StartLine,
		&i.EndLine,
		&i.Symbol,
		&i.Category,
		&i.ConfidenceTier,
		&i.ConfidenceScore,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.Suggestion,
		&i.LocationHash,
		&i.ContentHash,
		&i.HeadSha,
		&i.PostedAt,
		&i.ExternalCommentID,
		&i.AddressedStatus,
		&i.SuppressionReason,
		&i.DismissedAt,
		&i.DismissedBy,
		&i.ModelID,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPriorFinding = `-- name: FindPriorFinding :one
SELECT id, location_hash, content_hash, head_sha FROM findings
WHERE pull_request_id = $1 AND location_hash = $2 AND addressed_status = 'unaddressed'
ORDER BY created_at DESC
LIMIT 1
`

type FindPriorFindingParams struct {
	PullRequestID uuid.UUID `json:"pull_request_id"`
	LocationHash  string    `json:"location_hash"`
}

type FindPriorFindingRow struct {
	ID           uuid.UUID   `json:"id"`
	LocationHash string      `json:"location_hash"`
	ContentHash  pgtype.Text `json:"content_hash"`
	HeadSha      string      `json:"head_sha"`
}

func (q *Queries) FindPriorFinding(ctx context.Context, arg FindPriorFindingParams) (FindPriorFindingRow, error) {
	row := q.db.QueryRow(ctx, findPriorFinding, arg.PullRequestID, arg.LocationHash)
	var i FindPriorFindingRow
	err := row.Scan(
		&i.ID,
		&i.LocationHash,
		&i.ContentHash,
		&i.HeadSha,
	)
	return i, err
}

const listFindingsForPR = `-- name: ListFindingsForPR :many
SELECT id, review_task_id, pull_request_id, pipeline_run_id, repo_full_name, file_path, start_line, end_line, symbol, category, confidence_tier, confidence_score, severity, title, body, suggestion, location_hash, content_hash, head_sha, posted_at, external_comment_id, addressed_status, suppression_reason, dismissed_at, dismissed_by, model_id, prompt_tokens, completion_tokens, metadata, created_at, updated_at FROM findings WHERE pull_request_id = $1
ORDER BY CASE severity
    WHEN 'critical' THEN 1
    WHEN 'high'     THEN 2
    WHEN 'medium'   THEN 3
    WHEN 'low'      THEN 4
    WHEN 'info'     THEN 5
END ASC, confidence_score DESC
`

func (q *Queries) ListFindingsForPR(ctx context.Context, pullRequestID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsForPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewTaskID,
			&i.PullRequestID,
			&i.PipelineRunID,
			&i.RepoFullName,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.Symbol,
			&i.Category,
			&i.ConfidenceTier,
			&i.ConfidenceScore,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Suggestion,
			&i.LocationHash,
			&i.ContentHash,
			&i.HeadSha,
			&i.PostedAt,
			&i.ExternalCommentID,
			&i.AddressedStatus,
			&i.SuppressionReason,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.ModelID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsForRun = `-- name: ListFindingsForRun :many
SELECT id, review_task_id, pull_request_id, pipeline_run_id, repo_full_name, file_path, start_line, end_line, symbol, category, confidence_tier, confidence_score, severity, title, body, suggestion, location_hash, content_hash, head_sha, posted_at, external_comment_id, addressed_status, suppression_reason, dismissed_at, dismissed_by, model_id, prompt_tokens, completion_tokens, metadata, created_at, updated_at FROM findings WHERE pipeline_run_id = $1
ORDER BY CASE severity
    WHEN 'critical' THEN 1
    WHEN 'high'     THEN 2
    WHEN 'medium'   THEN 3
    WHEN 'low'      THEN 4
    WHEN 'info'     THEN 5
END ASC, confidence_score DESC
`

func (q *Queries) ListFindingsForRun(ctx context.Context, pipelineRunID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsForRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewTaskID,
			&i.PullRequestID,
			&i.PipelineRunID,
			&i.RepoFullName,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.Symbol,
			&i.Category,
			&i.ConfidenceTier,
			&i.ConfidenceScore,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Suggestion,
			&i.LocationHash,
			&i.ContentHash,
			&i.HeadSha,
			&i.PostedAt,
			&i.ExternalCommentID,
			&i.AddressedStatus,
			&i.SuppressionReason,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.ModelID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnaddressedFindingsForPR = `-- name: ListUnaddressedFindingsForPR :many
SELECT id, review_task_id, pull_request_id, pipeline_run_id, repo_full_name, file_path, start_line, end_line, symbol, category, confidence_tier, confidence_score, severity, title, body, suggestion, location_hash, content_hash, head_sha, posted_at, external_comment_id, addressed_status, suppression_reason, dismissed_at, dismissed_by, model_id, prompt_tokens, completion_tokens, metadata, created_at, updated_at FROM findings
WHERE pull_request_id = $1
  AND addressed_status = 'unaddressed'
  AND content_hash IS NOT NULL
`

func (q *Queries) ListUnaddressedFindingsForPR(ctx context.Context, pullRequestID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listUnaddressedFindingsForPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewTaskID,
			&i.PullRequestID,
			&i.PipelineRunID,
			&i.RepoFullName,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.Symbol,
			&i.Category,
			&i.ConfidenceTier,
			&i.ConfidenceScore,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Suggestion,
			&i.LocationHash,
			&i.ContentHash,
			&i.HeadSha,
			&i.PostedAt,
			&i.ExternalCommentID,
			&i.AddressedStatus,
			&i.SuppressionReason,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.ModelID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpostedFindings = `-- name: ListUnpostedFindings :many
SELECT f.id, f.review_task_id, f.pull_request_id, f.pipeline_run_id, f.repo_full_name, f.file_path, f.start_line, f.end_line, f.symbol, f.category, f.confidence_tier, f.confidence_score, f.severity, f.title, f.body, f.suggestion, f.location_hash, f.content_hash, f.head_sha, f.posted_at, f.external_comment_id, f.addressed_status, f.suppression_reason, f.dismissed_at, f.dismissed_by, f.model_id, f.prompt_tokens, f.completion_tokens, f.metadata, f.created_at, f.updated_at FROM findings f
JOIN pipeline_runs pr ON pr.id = f.pipeline_run_id
WHERE f.pipeline_run_id = $1
  AND f.posted_at IS NULL
  AND f.suppression_reason IS NULL
  AND f.external_comment_id IS NULL
  AND pr.status = 'completed'
ORDER BY f.created_at ASC
`

// Finds findings that were persisted but never posted to GitHub.
// Used by the PostingRetryJob to recover from GitHub API failures.
// Scoped by pipeline_run_id per CLAUDE.md boundary rule.
func (q *Queries) ListUnpostedFindings(ctx context.Context, pipelineRunID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listUnpostedFindings, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Finding{}
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ReviewTaskID,
			&i.PullRequestID,
			&i.PipelineRunID,
			&i.RepoFullName,
			&i.FilePath,
			&i.StartLine,
			&i.EndLine,
			&i.Symbol,
			&i.Category,
			&i.ConfidenceTier,
			&i.ConfidenceScore,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Suggestion,
			&i.LocationHash,
			&i.ContentHash,
			&i.HeadSha,
			&i.PostedAt,
			&i.ExternalCommentID,
			&i.AddressedStatus,
			&i.SuppressionReason,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.ModelID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFindingAddressed = `-- name: MarkFindingAddressed :execrows
UPDATE findings SET addressed_status = $2, updated_at = now() WHERE id = $1
`

type MarkFindingAddressedParams struct {
	ID              uuid.UUID `json:"id"`
	AddressedStatus string    `json:"addressed_status"`
}

func (q *Queries) MarkFindingAddressed(ctx context.Context, arg MarkFindingAddressedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFindingAddressed, arg.ID, arg.AddressedStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFindingPosted = `-- name: MarkFindingPosted :execrows
UPDATE findings SET posted_at = now(), external_comment_id = $2, updated_at = now() WHERE id = $1
`

type MarkFindingPostedParams struct {
	ID                uuid.UUID   `json:"id"`
	ExternalCommentID pgtype.Int8 `json:"external_comment_id"`
}

func (q *Queries) MarkFindingPosted(ctx context.Context, arg MarkFindingPostedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFindingPosted, arg.ID, arg.ExternalCommentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
