// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DismissedFingerprint struct {
	Fingerprint  string      `json:"fingerprint"`
	RepoFullName string      `json:"repo_full_name"`
	DismissedBy  string      `json:"dismissed_by"`
	Reason       pgtype.Text `json:"reason"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Finding struct {
	ID                    uuid.UUID       `json:"id"`
	ReviewTaskID          uuid.UUID       `json:"review_task_id"`
	PullRequestID         uuid.UUID       `json:"pull_request_id"`
	FilePath              string          `json:"file_path"`
	StartLine             pgtype.Int4     `json:"start_line"`
	EndLine               pgtype.Int4     `json:"end_line"`
	Symbol                pgtype.Text     `json:"symbol"`
	Category              string          `json:"category"`
	ConfidenceTier        string          `json:"confidence_tier"`
	ConfidenceScore       float64         `json:"confidence_score"`
	Severity              string          `json:"severity"`
	Title                 string          `json:"title"`
	Body                  string          `json:"body"`
	Suggestion            pgtype.Text     `json:"suggestion"`
	LocationHash          string          `json:"location_hash"`
	ContentHash           pgtype.Text     `json:"content_hash"`
	PostedAt              *time.Time      `json:"posted_at"`
	GithubCommentID       pgtype.Int8     `json:"github_comment_id"`
	AddressedInNextCommit bool            `json:"addressed_in_next_commit"`
	DismissedAt           *time.Time      `json:"dismissed_at"`
	DismissedBy           pgtype.Text     `json:"dismissed_by"`
	ModelID               string          `json:"model_id"`
	PromptTokens          pgtype.Int4     `json:"prompt_tokens"`
	CompletionTokens      pgtype.Int4     `json:"completion_tokens"`
	Metadata              json.RawMessage `json:"metadata"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type PullRequest struct {
	ID           uuid.UUID       `json:"id"`
	GithubPrID   int64           `json:"github_pr_id"`
	RepoFullName string          `json:"repo_full_name"`
	PrNumber     int32           `json:"pr_number"`
	HeadSha      string          `json:"head_sha"`
	BaseSha      string          `json:"base_sha"`
	Author       string          `json:"author"`
	State        string          `json:"state"`
	Metadata     json.RawMessage `json:"metadata"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ReviewTask struct {
	ID            uuid.UUID   `json:"id"`
	PullRequestID uuid.UUID   `json:"pull_request_id"`
	TaskType      string      `json:"task_type"`
	FilePath      string      `json:"file_path"`
	Symbol        pgtype.Text `json:"symbol"`
	RiskScore     float64     `json:"risk_score"`
	Status        string      `json:"status"`
	Error         pgtype.Text `json:"error"`
	StartedAt     *time.Time  `json:"started_at"`
	CompletedAt   *time.Time  `json:"completed_at"`
	CreatedAt     time.Time   `json:"created_at"`
}
