// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline_runs.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePipelineRun = `-- name: CompletePipelineRun :execrows
UPDATE pipeline_runs
SET status        = $2,
    task_count    = $3,
    finding_count = $4,
    error         = $5,
    completed_at  = now()
WHERE id = $1
`

type CompletePipelineRunParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	TaskCount    int32       `json:"task_count"`
	FindingCount int32       `json:"finding_count"`
	Error        pgtype.Text `json:"error"`
}

func (q *Queries) CompletePipelineRun(ctx context.Context, arg CompletePipelineRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePipelineRun,
		arg.ID,
		arg.Status,
		arg.TaskCount,
		arg.FindingCount,
		arg.Error,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPipelineRun = `-- name: CreatePipelineRun :one
INSERT INTO pipeline_runs (
    id, pull_request_id, head_sha, status,
    prompt_version, config_hash, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING created_at, updated_at
`

type CreatePipelineRunParams struct {
	ID            uuid.UUID       `json:"id"`
	PullRequestID uuid.UUID       `json:"pull_request_id"`
	HeadSha       string          `json:"head_sha"`
	Status        string          `json:"status"`
	PromptVersion string          `json:"prompt_version"`
	ConfigHash    string          `json:"config_hash"`
	Metadata      json.RawMessage `json:"metadata"`
}

type CreatePipelineRunRow struct {
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (CreatePipelineRunRow, error) {
	row := q.db.QueryRow(ctx, createPipelineRun,
		arg.ID,
		arg.PullRequestID,
		arg.HeadSha,
		arg.Status,
		arg.PromptVersion,
		arg.ConfigHash,
		arg.Metadata,
	)
	var i CreatePipelineRunRow
	err := row.Scan(&i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getPipelineRun = `-- name: GetPipelineRun :one
SELECT id, pull_request_id, head_sha, status,
       prompt_version, config_hash,
       task_count, finding_count, error, metadata,
       started_at, completed_at, created_at, updated_at
FROM pipeline_runs
WHERE id = $1
`

func (q *Queries) GetPipelineRun(ctx context.Context, id uuid.UUID) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, getPipelineRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.Status,
		&i.PromptVersion,
		&i.ConfigHash,
		&i.TaskCount,
		&i.FindingCount,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPipelineRunsForPR = `-- name: ListPipelineRunsForPR :many
SELECT id, pull_request_id, head_sha, status,
       prompt_version, config_hash,
       task_count, finding_count, error, metadata,
       started_at, completed_at, created_at, updated_at
FROM pipeline_runs
WHERE pull_request_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPipelineRunsForPR(ctx context.Context, pullRequestID uuid.UUID) ([]PipelineRun, error) {
	rows, err := q.db.Query(ctx, listPipelineRunsForPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.HeadSha,
			&i.Status,
			&i.PromptVersion,
			&i.ConfigHash,
			&i.TaskCount,
			&i.FindingCount,
			&i.Error,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileStalePipelineRuns = `-- name: ReconcileStalePipelineRuns :execrows
UPDATE pipeline_runs
SET status       = 'failed',
    error        = 'reconciled: process crashed or restarted',
    completed_at = now()
WHERE status = 'running'
`

func (q *Queries) ReconcileStalePipelineRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileStalePipelineRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
