// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline_runs.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completePipelineRun = `-- name: CompletePipelineRun :exec
UPDATE pipeline_runs
SET status = $2, tasks_total = $3, tasks_completed = $4, tasks_failed = $5,
    findings_total = $6, findings_posted = $7, findings_suppressed = $8,
    completed_at = now()
WHERE id = $1
`

type CompletePipelineRunParams struct {
	ID                 uuid.UUID   `json:"id"`
	Status             string      `json:"status"`
	TasksTotal         pgtype.Int4 `json:"tasks_total"`
	TasksCompleted     pgtype.Int4 `json:"tasks_completed"`
	TasksFailed        pgtype.Int4 `json:"tasks_failed"`
	FindingsTotal      pgtype.Int4 `json:"findings_total"`
	FindingsPosted     pgtype.Int4 `json:"findings_posted"`
	FindingsSuppressed pgtype.Int4 `json:"findings_suppressed"`
}

func (q *Queries) CompletePipelineRun(ctx context.Context, arg CompletePipelineRunParams) error {
	_, err := q.db.Exec(ctx, completePipelineRun,
		arg.ID,
		arg.Status,
		arg.TasksTotal,
		arg.TasksCompleted,
		arg.TasksFailed,
		arg.FindingsTotal,
		arg.FindingsPosted,
		arg.FindingsSuppressed,
	)
	return err
}

const createPipelineRun = `-- name: CreatePipelineRun :one
INSERT INTO pipeline_runs (pull_request_id, head_sha, prompt_version, config_hash, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, pull_request_id, head_sha, prompt_version, config_hash, status, tasks_total, tasks_completed, tasks_failed, findings_total, findings_posted, findings_suppressed, started_at, completed_at, metadata
`

type CreatePipelineRunParams struct {
	PullRequestID uuid.UUID       `json:"pull_request_id"`
	HeadSha       string          `json:"head_sha"`
	PromptVersion string          `json:"prompt_version"`
	ConfigHash    string          `json:"config_hash"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, createPipelineRun,
		arg.PullRequestID,
		arg.HeadSha,
		arg.PromptVersion,
		arg.ConfigHash,
		arg.Metadata,
	)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.PromptVersion,
		&i.ConfigHash,
		&i.Status,
		&i.TasksTotal,
		&i.TasksCompleted,
		&i.TasksFailed,
		&i.FindingsTotal,
		&i.FindingsPosted,
		&i.FindingsSuppressed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const getPipelineRun = `-- name: GetPipelineRun :one
SELECT id, pull_request_id, head_sha, prompt_version, config_hash, status, tasks_total, tasks_completed, tasks_failed, findings_total, findings_posted, findings_suppressed, started_at, completed_at, metadata FROM pipeline_runs WHERE id = $1
`

func (q *Queries) GetPipelineRun(ctx context.Context, id uuid.UUID) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, getPipelineRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.HeadSha,
		&i.PromptVersion,
		&i.ConfigHash,
		&i.Status,
		&i.TasksTotal,
		&i.TasksCompleted,
		&i.TasksFailed,
		&i.FindingsTotal,
		&i.FindingsPosted,
		&i.FindingsSuppressed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const listPipelineRunsForPR = `-- name: ListPipelineRunsForPR :many
SELECT id, pull_request_id, head_sha, prompt_version, config_hash, status, tasks_total, tasks_completed, tasks_failed, findings_total, findings_posted, findings_suppressed, started_at, completed_at, metadata FROM pipeline_runs WHERE pull_request_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListPipelineRunsForPR(ctx context.Context, pullRequestID uuid.UUID) ([]PipelineRun, error) {
	rows, err := q.db.Query(ctx, listPipelineRunsForPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.HeadSha,
			&i.PromptVersion,
			&i.ConfigHash,
			&i.Status,
			&i.TasksTotal,
			&i.TasksCompleted,
			&i.TasksFailed,
			&i.FindingsTotal,
			&i.FindingsPosted,
			&i.FindingsSuppressed,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileStalePipelineRuns = `-- name: ReconcileStalePipelineRuns :exec
UPDATE pipeline_runs
SET status = 'failed',
    completed_at = now(),
    metadata = metadata || '{"failure_reason": "abandoned: process crash or timeout"}'::jsonb
WHERE status = 'running'
  AND started_at < now() - $1::interval
`

func (q *Queries) ReconcileStalePipelineRuns(ctx context.Context, dollar_1 pgtype.Interval) error {
	_, err := q.db.Exec(ctx, reconcileStalePipelineRuns, dollar_1)
	return err
}
