// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getPullRequest = `-- name: GetPullRequest :one
SELECT id, external_pr_id, repo_full_name, pr_number,
       head_sha, base_sha, author, state, metadata,
       deleted_at, created_at, updated_at
FROM pull_requests
WHERE id = $1
`

func (q *Queries) GetPullRequest(ctx context.Context, id uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequest, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.ExternalPrID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.BaseSha,
		&i.Author,
		&i.State,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeletePullRequest = `-- name: SoftDeletePullRequest :execrows
UPDATE pull_requests
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePullRequest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePullRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPullRequest = `-- name: UpsertPullRequest :one
INSERT INTO pull_requests (
    id, external_pr_id, repo_full_name, pr_number,
    head_sha, base_sha, author, state, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (external_pr_id, head_sha)
DO UPDATE SET
    state      = EXCLUDED.state,
    metadata   = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, created_at, updated_at
`

type UpsertPullRequestParams struct {
	ID           uuid.UUID       `json:"id"`
	ExternalPrID   int64           `json:"external_pr_id"`
	RepoFullName string          `json:"repo_full_name"`
	PrNumber     int32           `json:"pr_number"`
	HeadSha      string          `json:"head_sha"`
	BaseSha      string          `json:"base_sha"`
	Author       string          `json:"author"`
	State        string          `json:"state"`
	Metadata     json.RawMessage `json:"metadata"`
}

type UpsertPullRequestRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (UpsertPullRequestRow, error) {
	row := q.db.QueryRow(ctx, upsertPullRequest,
		arg.ID,
		arg.ExternalPrID,
		arg.RepoFullName,
		arg.PrNumber,
		arg.HeadSha,
		arg.BaseSha,
		arg.Author,
		arg.State,
		arg.Metadata,
	)
	var i UpsertPullRequestRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
