// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getPullRequest = `-- name: GetPullRequest :one
SELECT id, external_pr_id, repo_full_name, pr_number, head_sha, base_sha, author, state, metadata, deleted_at, created_at, updated_at FROM pull_requests WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPullRequest(ctx context.Context, id uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequest, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.ExternalPrID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.BaseSha,
		&i.Author,
		&i.State,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequestByGitHubID = `-- name: GetPullRequestByGitHubID :one
SELECT id, external_pr_id, repo_full_name, pr_number, head_sha, base_sha, author, state, metadata, deleted_at, created_at, updated_at FROM pull_requests
WHERE external_pr_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPullRequestByGitHubID(ctx context.Context, externalPrID int64) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequestByGitHubID, externalPrID)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.ExternalPrID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.BaseSha,
		&i.Author,
		&i.State,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeletePullRequest = `-- name: SoftDeletePullRequest :execrows
UPDATE pull_requests SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePullRequest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePullRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPullRequest = `-- name: UpsertPullRequest :one
INSERT INTO pull_requests (external_pr_id, repo_full_name, pr_number, head_sha, base_sha, author, state, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (external_pr_id, head_sha) DO UPDATE
SET state = EXCLUDED.state, metadata = EXCLUDED.metadata, updated_at = now()
RETURNING id, external_pr_id, repo_full_name, pr_number, head_sha, base_sha, author, state, metadata, deleted_at, created_at, updated_at
`

type UpsertPullRequestParams struct {
	ExternalPrID int64           `json:"external_pr_id"`
	RepoFullName string          `json:"repo_full_name"`
	PrNumber     int32           `json:"pr_number"`
	HeadSha      string          `json:"head_sha"`
	BaseSha      string          `json:"base_sha"`
	Author       string          `json:"author"`
	State        string          `json:"state"`
	Metadata     json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, upsertPullRequest,
		arg.ExternalPrID,
		arg.RepoFullName,
		arg.PrNumber,
		arg.HeadSha,
		arg.BaseSha,
		arg.Author,
		arg.State,
		arg.Metadata,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.ExternalPrID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.BaseSha,
		&i.Author,
		&i.State,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
