// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_tasks.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewTask = `-- name: CreateReviewTask :one
INSERT INTO review_tasks (
    id, pull_request_id, task_type, file_path, symbol, risk_score, status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING created_at
`

type CreateReviewTaskParams struct {
	ID            uuid.UUID   `json:"id"`
	PullRequestID uuid.UUID   `json:"pull_request_id"`
	TaskType      string      `json:"task_type"`
	FilePath      string      `json:"file_path"`
	Symbol        pgtype.Text `json:"symbol"`
	RiskScore     float64     `json:"risk_score"`
	Status        string      `json:"status"`
}

func (q *Queries) CreateReviewTask(ctx context.Context, arg CreateReviewTaskParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createReviewTask,
		arg.ID,
		arg.PullRequestID,
		arg.TaskType,
		arg.FilePath,
		arg.Symbol,
		arg.RiskScore,
		arg.Status,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listPendingReviewTasks = `-- name: ListPendingReviewTasks :many
SELECT id, pull_request_id, task_type, file_path, symbol,
       risk_score, status, error, started_at, completed_at, created_at
FROM review_tasks
WHERE status = 'pending'
ORDER BY risk_score DESC
`

func (q *Queries) ListPendingReviewTasks(ctx context.Context) ([]ReviewTask, error) {
	rows, err := q.db.Query(ctx, listPendingReviewTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewTask{}
	for rows.Next() {
		var i ReviewTask
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.TaskType,
			&i.FilePath,
			&i.Symbol,
			&i.RiskScore,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewTaskStatusOther = `-- name: UpdateReviewTaskStatusOther :execrows
UPDATE review_tasks
SET status = $2
WHERE id = $1
`

type UpdateReviewTaskStatusOtherParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateReviewTaskStatusOther(ctx context.Context, arg UpdateReviewTaskStatusOtherParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReviewTaskStatusOther, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReviewTaskStatusRunning = `-- name: UpdateReviewTaskStatusRunning :execrows
UPDATE review_tasks
SET status = $2, started_at = now()
WHERE id = $1
`

type UpdateReviewTaskStatusRunningParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateReviewTaskStatusRunning(ctx context.Context, arg UpdateReviewTaskStatusRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReviewTaskStatusRunning, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReviewTaskStatusTerminal = `-- name: UpdateReviewTaskStatusTerminal :execrows
UPDATE review_tasks
SET status = $2, error = $3, completed_at = now()
WHERE id = $1
`

type UpdateReviewTaskStatusTerminalParams struct {
	ID     uuid.UUID   `json:"id"`
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
}

func (q *Queries) UpdateReviewTaskStatusTerminal(ctx context.Context, arg UpdateReviewTaskStatusTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReviewTaskStatusTerminal, arg.ID, arg.Status, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
